"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "ar" | "hi" | "fr" | "es" | "de" | "zh";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  dir: "ltr" | "rtl";
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    brand: "ALLOR RAIN",
    statusNominal: "SYSTEM: NOMINAL",
    statusActive: "ATMOSPHERIC INJECTION: ACTIVE",
    lat: "LAT: 24.4518° N",
    lon: "LON: 54.3774° E",
    navHome: "Home",
    navTech: "Technology",
    navResearch: "Research",
    navClimate: "Climate Intelligence",
    navSolutions: "Solutions",
    navCases: "Case Studies",
    navGov: "Government Programs",
    navSustain: "Sustainability",
    navInvestors: "Investors",
    navNews: "News",
    navCareers: "Careers",
    navContact: "Contact",
    btnTriggerRain: "TRIGGER PRECIPITATION",
    btnStopRain: "ENGAGED - COLLAPSE CLOUD",

    // Hero / Atmosphere
    heroTitle: "Atmospheric Intelligence",
    heroSubtitle: "Generating natural rainfall to secure freshwater sovereignty in drought-prone regions.",
    scrollPrompt: "SCROLL TO DESCEND INTO ATMOSPHERE",

    // Problem
    probTitle: "The Hydrological Crisis",
    probSubtitle: "Freshwater is depleting faster than nature can replenish it.",
    probStat1: "2.3 Billion",
    probLabel1: "People living under water-stress",
    probStat2: "1.8x",
    probLabel2: "Global aquifer depletion rate",
    probStat3: "40%",
    probLabel3: "Reduction in agricultural yields by 2030",

    // Science
    sciTitle: "Atmospheric Coalescence",
    sciSubtitle: "Our technology works with existing cloud physics, charging moisture particles to trigger natural coalescence.",
    sciStep1Title: "1. Electrostatic Ionization",
    sciStep1Desc: "Ground-based arrays emit high-velocity ions to electrify moisture-bearing air masses.",
    sciStep2Title: "2. Cloud Physics Coalescence",
    sciStep2Desc: "Electrostatically charged water droplets attract each other, forming heavier rain droplets.",
    sciStep3Title: "3. Precision Precipitation",
    sciStep3Desc: "Targeted precipitation falls precisely over designated catchment basins, verified by satellite telemetry.",

    // Configurator
    configTitle: "Sovereign Precipitation Configurator",
    configSubtitle: "Simulation parameters for government agencies to estimate water generation outputs.",
    paramDrought: "Drought Severity Index",
    paramHumidity: "Atmospheric Humidity",
    paramArea: "Target Area Radius",
    paramIonization: "Ionization Field Charge",
    resultEstVolume: "Estimated Water Volume",
    resultEstCost: "Operational Investment",
    resultEstTime: "Precipitation Lead Time",
    btnConfigure: "CALCULATE FEASIBILITY",
    valHigh: "Critical",
    valMedium: "Moderate",
    valLow: "Low",

    // Coexistence / Sustainability
    ecoTitle: "Ecological Integration",
    ecoSubtitle: "Advanced weather modification must respect biodiversity. Our systems are engineered for safety.",
    ecoStat1: "100%",
    ecoLabel1: "Chemical-free execution (No Silver Iodide)",
    ecoStat2: "Zero",
    ecoLabel2: "Long-term soil or biological toxicity",
    ecoStat3: "+18%",
    ecoLabel3: "Local biodiversity index improvement",

    // Case Studies
    caseTitle: "Global Deployments",
    caseSubtitle: "Empirical proof of concept across desert terrains, highlands, and agricultural zones.",
    case1Title: "Al Hajar Mountain Range, UAE",
    case1Desc: "Increased local catchment aquifer recharge by 24.3% over a 12-month cycle.",
    case2Title: "Najd Plateau, Saudi Arabia",
    case2Desc: "Restored 15,000 hectares of arid agricultural soils via scheduled precipitation runs.",
    case3Title: "Murray-Darling Basin, Australia",
    case3Desc: "Mitigated severe river basin drying, protecting local ecosystems and agricultural yields.",

    // Footer
    footNotice: "ALLOR RAIN Systems. Standardized under planetary environmental compliance protocols. Security Level A-1.",
    footCopy: "© 2026 ALLOR RAIN. Advanced Weather Engineering Systems.",
  },
  ar: {
    // Nav
    brand: "آلور رين",
    statusNominal: "النظام: طبيعي",
    statusActive: "الحقن الجوي: نشط",
    lat: "عرض: 24.4518° شمالاً",
    lon: "طول: 54.3774° شرقاً",
    navHome: "الرئيسية",
    navTech: "التقنية",
    navResearch: "الأبحاث",
    navClimate: "ذكاء المناخ",
    navSolutions: "الحلول",
    navCases: "دراسات الحالة",
    navGov: "البرامج الحكومية",
    navSustain: "الاستدامة",
    navInvestors: "المستثمرون",
    navNews: "الأخبار",
    navCareers: "الوظائف",
    navContact: "الاتصال",
    btnTriggerRain: "تنشيط هطول الأمطار",
    btnStopRain: "نشط - إنهاء هطول الأمطار",

    // Hero / Atmosphere
    heroTitle: "ذكاء الغلاف الجوي",
    heroSubtitle: "توليد هطول الأمطار الطبيعي لتأمين السيادة المائية العذبة في المناطق المعرضة للجفاف.",
    scrollPrompt: "مرر للأسفل للدخول إلى الغلاف الجوي",

    // Problem
    probTitle: "أزمة المياه الهيدرولوجية",
    probSubtitle: "تستنفد المياه العذبة بمعدل أسرع مما يمكن للطبيعة تجديده.",
    probStat1: "2.3 مليار",
    probLabel1: "شخص يعيشون تحت وطأة الشح المائي",
    probStat2: "1.8 ضعف",
    probLabel2: "معدل نضوب طبقات المياه الجوفية عالمياً",
    probStat3: "40%",
    probLabel3: "انخفاض في المحاصيل الزراعية بحلول عام 2030",

    // Science
    sciTitle: "الاندماج الجوي",
    sciSubtitle: "تعمل تقنيتنا بالتوافق مع فيزياء السحب الحالية، حيث تشحن جزيئات الرطوبة لتحفيز الاندماج الطبيعي.",
    sciStep1Title: "١. التأين الكهروستاتيكي",
    sciStep1Desc: "تطلق المصفوفات الأرضية أيونات عالية السرعة لكهربة الكتل الهوائية الحاملة للرطوبة.",
    sciStep2Title: "٢. اندماج فيزياء السحاب",
    sciStep2Desc: "تتجاذب قطرات الماء المشحونة كهروستاتيكياً، مما يؤدي لتكوين قطرات مطر أثقل.",
    sciStep3Title: "٣. الهطول الدقيق للمطر",
    sciStep3Desc: "يهطل المطر الموجه بدقة فوق أحواض التجميع المحددة، ويتم التحقق منه عبر القياس الفضائي.",

    // Configurator
    configTitle: "أداة تهيئة الأمطار السيادية",
    configSubtitle: "معايير المحاكاة للهيئات الحكومية لتقدير مخرجات توليد المياه.",
    paramDrought: "مؤشر شدة الجفاف",
    paramHumidity: "رطوبة الغلاف الجوي",
    paramArea: "نطاق المنطقة المستهدفة",
    paramIonization: "شحنة حقل التأين",
    resultEstVolume: "حجم المياه التقديري",
    resultEstCost: "الاستثمار التشغيلي",
    resultEstTime: "وقت الاستجابة للهطول",
    btnConfigure: "احسب الجدوى",
    valHigh: "حرِج",
    valMedium: "متوسط",
    valLow: "منخفض",

    // Coexistence / Sustainability
    ecoTitle: "التكامل البيئي",
    ecoSubtitle: "تعديل الطقس المتقدم يجب أن يحترم التنوع البيولوجي. أنظمتنا مصممة للأمان الكامل.",
    ecoStat1: "100%",
    ecoLabel1: "تنفيذ خالٍ من المواد الكيميائية (لا يوديد فضة)",
    ecoStat2: "صفر",
    ecoLabel2: "سمية بيولوجية أو تربية طويلة الأمد",
    ecoStat3: "+18%",
    ecoLabel3: "تحسن في مؤشر التنوع البيولوجي المحلي",

    // Case Studies
    caseTitle: "عمليات الانتشار العالمية",
    caseSubtitle: "إثبات تجريبي للمفهوم عبر التضاريس الصحراوية، المرتفعات، والمناطق الزراعية.",
    case1Title: "سلسلة جبال الحجر، الإمارات",
    case1Desc: "زيادة إعادة شحن المياه الجوفية المحلية بنسبة 24.3% على مدار دورة مدتها 12 شهراً.",
    case2Title: "هضبة نجد، المملكة العربية السعودية",
    case2Desc: "استصلاح 15,000 هكتار من الأراضي الزراعية الجافة من خلال هطول الأمطار المجدول.",
    case3Title: "حوض موراي دارلينغ، أستراليا",
    case3Desc: "تخفيف جفاف حوض النهر الشديد، وحماية الأنظمة البيئية المحلية والمحاصيل الزراعية.",

    // Footer
    footNotice: "أنظمة آلور رين. معتمدة بموجب بروتوكولات الامتثال البيئي الكوكبي. مستوى الأمان A-1.",
    footCopy: "© 2026 آلور رين. أنظمة هندسة الطقس المتقدمة.",
  },
  hi: {
    // Nav
    brand: "एलोर रेन",
    statusNominal: "सिस्टम: सामान्य",
    statusActive: "वायुमंडलीय इंजेक्शन: सक्रिय",
    lat: "अक्षांश: 24.4518° N",
    lon: "देशांतर: 54.3774° E",
    navHome: "होम",
    navTech: "तकनीक",
    navResearch: "अनुसंधान",
    navClimate: "जलवायु खुफिया",
    navSolutions: "समाधान",
    navCases: "केस स्टडीज",
    navGov: "सरकारी कार्यक्रम",
    navSustain: "सतत विकास",
    navInvestors: "निवेशक",
    navNews: "समाचार",
    navCareers: "करियर",
    navContact: "संपर्क",
    btnTriggerRain: "वर्षा सक्रिय करें",
    btnStopRain: "सक्रिय - वर्षा रोकें",

    // Hero / Atmosphere
    heroTitle: "वायुमंडलीय बुद्धिमत्ता",
    heroSubtitle: "सूखाग्रस्त क्षेत्रों में मीठे पानी की संप्रभुता सुरक्षित करने के लिए प्राकृतिक वर्षा का निर्माण।",
    scrollPrompt: "वायुमंडल में उतरने के लिए स्क्रॉल करें",

    // Problem
    probTitle: "जल संकट",
    probSubtitle: "मीठा पानी प्रकृति की तुलना में तेजी से समाप्त हो रहा है।",
    probStat1: "2.3 अरब",
    probLabel1: "पानी की कमी से जूझ रहे लोग",
    probStat2: "1.8 गुना",
    probLabel2: "वैश्विक भूजल निक्षेपण दर",
    probStat3: "40%",
    probLabel3: "2030 तक कृषि उत्पादन में कमी",

    // Science
    sciTitle: "वायुमंडलीय संघनन",
    sciSubtitle: "हमारी तकनीक बादलों के भौतिक विज्ञान के साथ काम करती है, नमी के कणों को आवेशित कर प्राकृतिक वर्षा को प्रेरित करती है।",
    sciStep1Title: "1. इलेक्ट्रोस्टैटिक आयनीकरण",
    sciStep1Desc: "सतही सरणियाँ नमी युक्त वायु को आवेशित करने के लिए तीव्र गति वाले आयन उत्सर्जित करती हैं।",
    sciStep2Title: "2. क्लाउड फिजिक्स संघनन",
    sciStep2Desc: "आवेशित पानी की बूंदें एक-दूसरे को आकर्षित करती हैं, जिससे भारी वर्षा की बूंदें बनती हैं।",
    sciStep3Title: "3. सटीक वर्षा",
    sciStep3Desc: "उपग्रह टेलीमेट्री द्वारा सत्यापित, वर्षा सटीक रूप से निर्दिष्ट जलग्रहण क्षेत्रों में होती है।",

    // Configurator
    configTitle: "संप्रभु वर्षा विन्यासकर्ता",
    configSubtitle: "सरकारी एजेंसियों के लिए पानी उत्पादन के अनुमान का सिम्युलेटर।",
    paramDrought: "सूखा सूचकांक",
    paramHumidity: "वायुमंडलीय आर्द्रता",
    paramArea: "लक्ष्य क्षेत्र त्रिज्या",
    paramIonization: "आयनीकरण क्षेत्र आवेश",
    resultEstVolume: "अनुमानित जल मात्रा",
    resultEstCost: "परिचालन निवेश",
    resultEstTime: "वर्षा की समय सीमा",
    btnConfigure: "व्यवहार्यता गणना करें",
    valHigh: "गंभीर",
    valMedium: "मध्यम",
    valLow: "कम",

    // Coexistence / Sustainability
    ecoTitle: "पारिस्थितिक एकीकरण",
    ecoSubtitle: "उन्नत मौसम संशोधन में जैव विविधता का सम्मान होना चाहिए। हमारे सिस्टम सुरक्षा के लिए डिज़ाइन किए गए हैं।",
    ecoStat1: "100%",
    ecoLabel1: "रसायन-मुक्त निष्पादन (सिल्वर आयोडाइड रहित)",
    ecoStat2: "शून्य",
    ecoLabel2: "दीर्घकालिक मिट्टी या जैविक विषाक्तता",
    ecoStat3: "+18%",
    ecoLabel3: "स्थानीय जैव विविधता सूचकांक में सुधार",

    // Case Studies
    caseTitle: "वैश्विक परिनियोजन",
    caseSubtitle: "रेगिस्तानी इलाकों, उच्च क्षेत्रों और कृषि क्षेत्रों में सफल प्रयोग का प्रामाणिक प्रमाण।",
    case1Title: "अल हजर पर्वत श्रृंखला, संयुक्त अरब अमीरात",
    case1Desc: "12 महीने के चक्र में स्थानीय भूजल रीचार्ज में 24.3% की वृद्धि।",
    case2Title: "नज्द पठार, सऊदी अरब",
    case2Desc: "निर्धारित वर्षा के माध्यम से 15,000 हेक्टेयर शुष्क कृषि भूमि का पुनरुद्धार।",
    case3Title: "मरे-डार्लिंग बेसिन, ऑस्ट्रेलिया",
    case3Desc: "नदी बेसिन के सूखने को कम किया, स्थानीय पारिस्थितिकी और फसलों की रक्षा की।",

    // Footer
    footNotice: "एलोर रेन सिस्टम। वैश्विक पर्यावरण नियमों के तहत प्रमाणित। सुरक्षा स्तर A-1।",
    footCopy: "© 2026 एलोर रेन। उन्नत मौसम इंजीनियरिंग प्रणालियाँ।",
  },
  fr: {
    brand: "ALLOR RAIN",
    statusNominal: "SYSTÈME: NOMINAL",
    statusActive: "INJECTION ATMOSPHÉRIQUE: ACTIVE",
    lat: "LAT: 24.4518° N",
    lon: "LON: 54.3774° E",
    navHome: "Accueil",
    navTech: "Technologie",
    navResearch: "Recherche",
    navClimate: "Intelligence Climat",
    navSolutions: "Solutions",
    navCases: "Études de cas",
    navGov: "Programmes d'État",
    navSustain: "Durabilité",
    navInvestors: "Investisseurs",
    navNews: "Actualités",
    navCareers: "Carrières",
    navContact: "Contact",
    btnTriggerRain: "DÉCLENCHER LA PLUIE",
    btnStopRain: "ENGAGÉ - EFFONDRER LE NUAGE",
    heroTitle: "Intelligence Atmosphérique",
    heroSubtitle: "Génération de pluie naturelle pour sécuriser la souveraineté en eau douce des zones arides.",
    scrollPrompt: "DÉFILEZ POUR DESCENDRE DANS L'ATMOSPHÈRE",
    probTitle: "La Crise Hydrologique",
    probSubtitle: "L'eau douce s'épuise plus vite que le rythme naturel de renouvellement.",
    probStat1: "2.3 Milliards",
    probLabel1: "De personnes vivent en stress hydrique",
    probStat2: "1.8x",
    probLabel2: "Taux d'épuisement des aquifères mondiaux",
    probStat3: "40%",
    probLabel3: "Baisse des rendements agricoles d'ici 2030",
    sciTitle: "Coalescence Atmosphérique",
    sciSubtitle: "Notre technologie s'appuie sur la physique des nuages existants pour charger les particules et déclencher la coalescence.",
    sciStep1Title: "1. Ionisation Électrostatique",
    sciStep1Desc: "Des réseaux au sol émettent des ions à haute vitesse pour électrifier les masses d'air humide.",
    sciStep2Title: "2. Coalescence Physique",
    sciStep2Desc: "Les gouttelettes chargées s'attirent mutuellement pour former des gouttes plus lourdes.",
    sciStep3Title: "3. Précipitations de Précision",
    sciStep3Desc: "Les pluies ciblées tombent précisément sur les bassins versants, validées par satellite.",
    configTitle: "Configurateur de Précipitation Souverain",
    configSubtitle: "Outil de simulation pour estimer les volumes de pluie générés.",
    paramDrought: "Indice de Sécheresse",
    paramHumidity: "Humidité Atmosphérique",
    paramArea: "Rayon de la Zone Cible",
    paramIonization: "Charge de l'Ionisation",
    resultEstVolume: "Volume d'Eau Estimé",
    resultEstCost: "Investissement Opérationnel",
    resultEstTime: "Délai de Précipitation",
    btnConfigure: "CALCULER LA FAISABILITÉ",
    valHigh: "Critique",
    valMedium: "Modéré",
    valLow: "Faible",
    ecoTitle: "Intégration Écologique",
    ecoSubtitle: "La modification du climat doit respecter la biodiversité. Nos systèmes sont sûrs.",
    ecoStat1: "100%",
    ecoLabel1: "Sans produits chimiques (Pas d'iodure d'argent)",
    ecoStat2: "Zéro",
    ecoLabel2: "Toxicité biologique ou des sols à long terme",
    ecoStat3: "+18%",
    ecoLabel3: "D'amélioration de l'index de biodiversité",
    caseTitle: "Déploiements Globaux",
    caseSubtitle: "Preuves empiriques d'efficacité en désert, montagne et zone agricole.",
    case1Title: "Chaîne des monts Hajar, Émirats",
    case1Desc: "Recharge des aquifères locaux en hausse de 24.3% sur un cycle de 12 mois.",
    case2Title: "Plateau du Najd, Arabie Saoudite",
    case2Desc: "Restauration de 15 000 hectares de terres agricoles arides par pluie planifiée.",
    case3Title: "Bassin Murray-Darling, Australie",
    case3Desc: "Atténuation de l'assèchement du bassin versant, protégeant l'écosystème local.",
    footNotice: "Systèmes ALLOR RAIN. Conformes aux protocoles environnementaux planétaires. Sécurité A-1.",
    footCopy: "© 2026 ALLOR RAIN. Ingénierie Atmosphérique Avancée.",
  },
  es: {
    brand: "ALLOR RAIN",
    statusNominal: "SISTEMA: NOMINAL",
    statusActive: "INYECCIÓN ATMOSFÉRICA: ACTIVA",
    lat: "LAT: 24.4518° N",
    lon: "LON: 54.3774° E",
    navHome: "Inicio",
    navTech: "Tecnología",
    navResearch: "Investigación",
    navClimate: "Inteligencia Climática",
    navSolutions: "Soluciones",
    navCases: "Casos de Estudio",
    navGov: "Programas Estatales",
    navSustain: "Sostenibilidad",
    navInvestors: "Inversores",
    navNews: "Noticias",
    navCareers: "Empleo",
    navContact: "Contacto",
    btnTriggerRain: "ACTIVAR PRECIPITACIÓN",
    btnStopRain: "ACTIVO - DETENER PRECIPITACIÓN",
    heroTitle: "Inteligencia Atmosférica",
    heroSubtitle: "Generación de lluvia natural para asegurar la soberanía de agua dulce en regiones áridas.",
    scrollPrompt: "DESPLACE PARA DESCENDER A LA ATMÓSFERA",
    probTitle: "La Crisis Hidrológica",
    probSubtitle: "El agua dulce se agota más rápido de lo que la naturaleza puede reponerla.",
    probStat1: "2.3 Mil Millones",
    probLabel1: "De personas viven bajo estrés hídrico",
    probStat2: "1.8x",
    probLabel2: "Tasa de agotamiento de acuíferos globales",
    probStat3: "40%",
    probLabel3: "Reducción de rendimientos agrícolas para 2030",
    sciTitle: "Coalescencia Atmosférica",
    sciSubtitle: "Nuestra tecnología trabaja con la física de nubes existente, cargando partículas para inducir la coalescencia natural.",
    sciStep1Title: "1. Ionización Electrostática",
    sciStep1Desc: "Redes en tierra emiten iones de alta velocidad para electrificar masas de aire húmedo.",
    sciStep2Title: "2. Coalescencia Física",
    sciStep2Desc: "Las gotas de agua cargadas se atraen mutuamente, formando gotas de lluvia pesadas.",
    sciStep3Title: "3. Precipitación de Precisión",
    sciStep3Desc: "Las lluvias caen con precisión sobre cuencas designadas, verificado por satélite.",
    configTitle: "Configurador de Precipitación Soberana",
    configSubtitle: "Parámetros de simulación para estimar la producción de agua generada.",
    paramDrought: "Índice de Sequía",
    paramHumidity: "Humedad Atmosférica",
    paramArea: "Radio del Área Objetivo",
    paramIonization: "Carga del Campo de Ionización",
    resultEstVolume: "Volumen de Agua Estimado",
    resultEstCost: "Inversión Operativa",
    resultEstTime: "Tiempo de Respuesta de Lluvia",
    btnConfigure: "CALCULAR VIABILIDAD",
    valHigh: "Crítico",
    valMedium: "Moderado",
    valLow: "Bajo",
    ecoTitle: "Integración Ecológica",
    ecoSubtitle: "La modificación del clima debe respetar la biodiversidad. Diseñado para ser seguro.",
    ecoStat1: "100%",
    ecoLabel1: "Libre de químicos (Sin yoduro de plata)",
    ecoStat2: "Cero",
    ecoLabel2: "Toxicidad biológica o del suelo a largo plazo",
    ecoStat3: "+18%",
    ecoLabel3: "De mejora en el índice de biodiversidad local",
    caseTitle: "Despliegues Globales",
    caseSubtitle: "Evidencia empírica de éxito en terrenos desérticos, montañosos y agrícolas.",
    case1Title: "Cordillera de Al Hajar, Emiratos Árabes",
    case1Desc: "Aumento del 24.3% en la recarga del acuífero local en un ciclo de 12 meses.",
    case2Title: "Meseta de Najd, Arabia Saudita",
    case2Desc: "Restauración de 15,000 hectáreas de tierras agrícolas áridas mediante lluvias programadas.",
    case3Title: "Cuenca Murray-Darling, Australia",
    case3Desc: "Mitigación de sequía severa en cuencas fluviales, protegiendo cosechas locales.",
    footNotice: "Sistemas ALLOR RAIN. Certificados bajo protocolos ambientales globales. Seguridad A-1.",
    footCopy: "© 2026 ALLOR RAIN. Sistemas Avanzados de Ingeniería del Clima.",
  },
  de: {
    brand: "ALLOR RAIN",
    statusNominal: "SYSTEM: NOMINAL",
    statusActive: "ATMOSPHERÄRISCHE INJEKTION: AKTIV",
    lat: "LAT: 24.4518° N",
    lon: "LON: 54.3774° E",
    navHome: "Startseite",
    navTech: "Technologie",
    navResearch: "Forschung",
    navClimate: "Klima-Intelligenz",
    navSolutions: "Lösungen",
    navCases: "Fallstudien",
    navGov: "Staatliche Programme",
    navSustain: "Nachhaltigkeit",
    navInvestors: "Investoren",
    navNews: "Aktuelles",
    navCareers: "Karriere",
    navContact: "Kontakt",
    btnTriggerRain: "REGEN AUSLÖSEN",
    btnStopRain: "AKTIV - REGEN BEENDEN",
    heroTitle: "Atmosphärische Intelligenz",
    heroSubtitle: "Erzeugung von natürlichem Regen zur Sicherung der Süßwassersouveränität in Dürregebieten.",
    scrollPrompt: "SCROLLEN, UM IN DIE ATMOSPHÄRE EINZUTAUCHEN",
    probTitle: "Die Hydrologische Krise",
    probSubtitle: "Süßwasser schwindet schneller, als die Natur es erneuern kann.",
    probStat1: "2.3 Milliarden",
    probLabel1: "Menschen leben in wasserarmen Gebieten",
    probStat2: "1.8x",
    probLabel2: "Globale Erschöpfungsrate der Grundwasserleiter",
    probStat3: "40%",
    probLabel3: "Rückgang der landwirtschaftlichen Erträge bis 2030",
    sciTitle: "Atmosphärische Koaleszenz",
    sciSubtitle: "Unsere Technologie arbeitet mit der bestehenden Wolkenphysik und lädt Feuchtigkeitspartikel auf, um natürliche Koaleszenz anzuregen.",
    sciStep1Title: "1. Elektrostatische Ionisation",
    sciStep1Desc: "Bodenstationen senden Hochgeschwindigkeits-Ionen aus, um feuchte Luftmassen aufzuladen.",
    sciStep2Title: "2. Wolkenkoaleszenz",
    sciStep2Desc: "Geladene Wassertropfen ziehen sich an und bilden schwerere Regentropfen.",
    sciStep3Title: "3. Präzisionsniederschlag",
    sciStep3Desc: "Zielgerichteter Regen fällt exakt über Auffangbecken, validiert durch Satellitendaten.",
    configTitle: "Souveräner Niederschlags-Konfigurator",
    configSubtitle: "Simulationswerkzeug für Regierungen zur Schätzung der Wassererträge.",
    paramDrought: "Dürreindex",
    paramHumidity: "Luftfeuchtigkeit",
    paramArea: "Radius des Zielgebiets",
    paramIonization: "Stärke des Ionisationsfeldes",
    resultEstVolume: "Geschätztes Wasservolumen",
    resultEstCost: "Betriebliche Investition",
    resultEstTime: "Niederschlagsreaktionszeit",
    btnConfigure: "MACHBARKEIT BERECHNEN",
    valHigh: "Kritisch",
    valMedium: "Moderat",
    valLow: "Gering",
    ecoTitle: "Ökologische Integration",
    ecoSubtitle: "Wetterbeeinflussung muss die biologische Vielfalt respektieren. Unsere Systeme sind sicher.",
    ecoStat1: "100%",
    ecoLabel1: "Chemiefreie Durchführung (Kein Silberiodid)",
    ecoStat2: "Null",
    ecoLabel2: "Langzeit-Boden- oder biologische Toxizität",
    ecoStat3: "+18%",
    ecoLabel3: "Verbesserung des lokalen Biodiversitätsindex",
    caseTitle: "Globale Einsätze",
    caseSubtitle: "Empirische Erfolgsnachweise in Wüsten, Hochland und Agrarzonen.",
    case1Title: "Hadschar-Gebirge, VAE",
    case1Desc: "Steigerung der Grundwasserneubildung um 24.3% in einem 12-monatigen Zyklus.",
    case2Title: "Najd-Plateau, Saudi-Arabien",
    case2Desc: "Wiederherstellung von 15.000 Hektar Agrarland durch geplanten Regen.",
    case3Title: "Murray-Darling-Becken, Australien",
    case3Desc: "Abschwächung der Austrocknung des Beckens, Schutz lokaler Ökosysteme.",
    footNotice: "ALLOR RAIN Systeme. Zertifiziert unter globalen Umweltstandards. Sicherheitsstufe A-1.",
    footCopy: "© 2026 ALLOR RAIN. Fortschrittliche Wettersystem-Ingenieure.",
  },
  zh: {
    brand: "ALLOR RAIN 埃罗雨",
    statusNominal: "系统状态: 正常",
    statusActive: "大气注入: 运行中",
    lat: "北纬: 24.4518° N",
    lon: "东经: 54.3774° E",
    navHome: "首页",
    navTech: "核心技术",
    navResearch: "研究中心",
    navClimate: "气候智能",
    navSolutions: "解决方案",
    navCases: "应用案例",
    navGov: "政府计划",
    navSustain: "可持续性",
    navInvestors: "投资者",
    navNews: "新闻动态",
    navCareers: "招贤纳士",
    navContact: "联系我们",
    btnTriggerRain: "触发人工降雨",
    btnStopRain: "已运行 - 终止降雨",
    heroTitle: "大气智能科技",
    heroSubtitle: "利用前沿大气工程技术创造自然降水，保障干旱地区的淡水主权。",
    scrollPrompt: "向下滚动进入地球大气层",
    probTitle: "全球水资源危机",
    probSubtitle: "全球淡水资源的消耗速度远超大自然的自我净化与补充速度。",
    probStat1: "23亿",
    probLabel1: "人口生活在极度缺水地区",
    probStat2: "1.8倍",
    probLabel2: "全球地下水消耗超出补充速率",
    probStat3: "40%",
    probLabel3: "预计到2030年农业产量将因此下降",
    sciTitle: "大气凝聚物理学",
    sciSubtitle: "我们的大气技术与现有的云物理学配合，通过对气流中水分粒子进行静电充电，触发自然凝聚降雨。",
    sciStep1Title: "1. 静电电离技术",
    sciStep1Desc: "地面电离阵列发射高速电荷粒子，使富含水分的空中气团带电。",
    sciStep2Title: "2. 云层物理凝聚",
    sciStep2Desc: "带静电的水滴相互吸引，聚合成较重的大雨滴。",
    sciStep3Title: "3. 精准降水调控",
    sciStep3Desc: "诱导的降水精准降落在指定集水区，降水结果由气象卫星遥测验证。",
    configTitle: "国家级降水模拟配置器",
    configSubtitle: "专为政府及水务机构设计的淡水生成产出估算模拟器。",
    paramDrought: "干旱严重指数",
    paramHumidity: "大气湿度水平",
    paramArea: "目标降雨半径",
    paramIonization: "电离场充电强度",
    resultEstVolume: "预计生成淡水总量",
    resultEstCost: "单次运营投资估算",
    resultEstTime: "降雨响应置信时间",
    btnConfigure: "进行可行性计算",
    valHigh: "重度干旱",
    valMedium: "中度干旱",
    valLow: "轻度",
    ecoTitle: "生态系统兼容集成",
    ecoSubtitle: "气候工程必须尊重和保护生物多样性。我们的技术体系专为生态安全而设计。",
    ecoStat1: "100%",
    ecoLabel1: "无化学药剂排放 (拒绝使用碘化银)",
    ecoStat2: "零残留",
    ecoLabel2: "对土壤或地表生物无长期毒性副作用",
    ecoStat3: "+18%",
    ecoLabel3: "促进当地生态生物多样性指数提升",
    caseTitle: "全球部署成果",
    caseSubtitle: "在荒漠、高原及灌溉农业区的大规模实证成功经验。",
    case1Title: "阿联酋哈杰尔山脉",
    case1Desc: "在12个月的项目周期内，促使当地集水区地下水回补量提升24.3%。",
    case2Title: "沙特阿拉伯内志高原",
    case2Desc: "通过定制的排程降水计划，使15,000公顷的荒漠化农田重获新生。",
    case3Title: "澳大利亚墨累-达令盆地",
    case3Desc: "有效缓解河流盆地严重干涸，保护了当地生态圈及农业作物的产量。",
    footNotice: "ALLOR RAIN 埃罗雨工程系统。完全符合全球行星环境合规标准。安全等级：A-1。",
    footCopy: "© 2026 ALLOR RAIN. 全球前沿天气工程系统。",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("allor_rain_lang") as Language;
    if (saved && translations[saved]) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    if (translations[lang]) {
      setLanguageState(lang);
      localStorage.setItem("allor_rain_lang", lang);
    }
  };

  const dir = language === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [dir, language]);

  const t = (key: string): string => {
    return translations[language][key] || translations["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, dir, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
